version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - static:/temp
    command: "cp -r dist /temp/frontend"
  backend:
    container_name: backend
    build: ./backend
    expose:
      - "8081"
    networks:
      - local-network
  web:
    container_name: web
    build: ./web
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx
    networks:
      - local-network
volumes:
  static:
networks:
  local-network:
