[package]
name = "mtasa-masterlist"
version = "0.1.0"
authors = ["nrzull <nrzull@tuta.io>"]
edition = "2018"
publish = false

[dependencies]
hyper = "0.12"
hyper-tls = "0.3.2"
bytes = "0.4.12"
byteorder = "1"
futures = "*"
