[package]
name = "mtasa-masterlist"
version = "0.1.0"
authors = ["nrzull <nrzull@tuta.io>"]
edition = "2018"
publish = false

[dependencies]
reqwest = "0.9.18"
bytes = "0.4.12"
byteorder = "1"
actix-web = "1.0.3"
serde = "1.0.94"
